CREATE DATABASE IF NOT EXISTS PROJETO_ONG;

DROP TABLE MENSAGEM;
DROP TABLE CHAT;
DROP TABLE FEEDBACKS;
DROP TABLE PALAVRAS_CHAVE;
DROP TABLE INTERESSES;
DROP TABLE ONGS;
DROP TABLE VOLUNTARIOS;
DROP TABLE REQUESTS_MUDAR_SENHA;
DROP TABLE CONTA;

SELECT * FROM VOLUNTARIOS;
SELECT * FROM ONGS;

USE PROJETO_ONG;
SELECT * FROM CONTA;
SELECT * FROM REQUESTS_MUDAR_SENHA;
delete from PROJETO_ONG.CONTA where EMAIL = 'fernando.affonso@connectparts.com.br';
delete from PROJETO_ONG.CONTA where EMAIL = 'thomedeiros@hotmail.com';
SELECT EMAIL, VERIFICADA FROM CONTA;
ALTER TABLE PROJETO_ONG.CONTA ADD DATA_ATUALIZACAO DATETIME NOT NULL DEFAULT NOW();
ALTER TABLE PROJETO_ONG.CONTA ADD IMAGEM_PERFIL VARCHAR(200) NOT NULL DEFAULT 'var/www/Projeto ONG/projeto_ong_files/profiles_images/defaults/default_profile_picture.png';
ALTER TABLE PROJETO_ONG.CONTA ADD IMAGEM_PERFIL VARCHAR(200) NOT NULL DEFAULT 'https://i.pinimg.com/736x/89/52/bf/8952bffb9c713b84a42217ab715170b2.jpg';
ALTER TABLE PROJETO_ONG.CONTA ADD IMAGEM_BANNER VARCHAR(200) NOT NULL DEFAULT 'var/www/Projeto ONG/projeto_ong_files/profiles_images/defaults/default_profile_banner.png';

ALTER TABLE PROJETO_ONG.PUBLICACAO ADD NOME VARCHAR(200) NOT NULL;
ALTER TABLE PROJETO_ONG.PUBLICACAO ADD SOBRENOME VARCHAR(200);

ALTER TABLE PROJETO_ONG.CONTA DROP COLUMN IMAGEM_PERFIL;
ALTER TABLE PROJETO_ONG.CONTA DROP COLUMN IMAGEM_BANNER;

SELECT * FROM PUBLICACAO LIMIT 0, 10;
UPDATE PUBLICACAO SET TEXTO = "Teste GIF", IMAGEM = "https://c.tenor.com/0Zrxg3b0nMwAAAAC/anime-girl.gif" WHERE TEXTO = 'None';
UPDATE PUBLICACAO SET NOME = "Fernando", SOBRENOME = "Hiibner" WHERE EMAIL = 'ferpinoti@gmail.com';

SELECT CONTA.*, VOLUNTARIO.*
FROM PROJETO_ONG.CONTA AS CONTA
INNER JOIN PROJETO_ONG.VOLUNTARIOS AS VOLUNTARIO
ON CONTA.EMAIL = VOLUNTARIO.EMAIL
WHERE CONTA.EMAIL = 'ferpinoti@gmail.com';

SELECT PUB.NOME
      ,PUB.SOBRENOME
      ,PUB.TEXTO
	  ,PUB.IMAGEM
      ,PUB.DATA_PUBLICACAO
      ,CONTA.IMAGEM_BANNER
      ,CONTA.IMAGEM_PERFIL 
 FROM PROJETO_ONG.PUBLICACAO AS PUB 
INNER JOIN PROJETO_ONG.CONTA AS CONTA
ON PUB.EMAIL = CONTA.EMAIL
WHERE PUB.EMAIL = 'ferpinoti@gmail.com'
ORDER BY PUB.DATA_PUBLICACAO DESC
LIMIT 0,10



SELECT CONTA.*, ONG.*
FROM PROJETO_ONG.CONTA AS CONTA
INNER JOIN PROJETO_ONG.ONGS AS ONG
ON CONTA.EMAIL = ONG.EMAIL
WHERE CONTA.EMAIL = 'heinrik.ivasaki@gmail.com';

SELECT COUNT(EMAIL) FROM CONTA WHERE EMAIL = 'thomaz@turbante.com.br';

INSERT INTO PROJETO_ONG.CONTA (EMAIL, SENHA, TIPO_CONTA, DATA_CRIACAO, HASH, VERIFICADA)
VALUES ('thomaz@turbante.com.br', '28s86d291378sds9', 'Voluntario', '2021-10-30 00:23:00', '219s8da9092890s', 0);



TRUNCATE TABLE PROJETO_ONG.CONTA;
